feat: use env variable

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -270,6 +270,7 @@ jobs:
     executor: ubuntu
     environment:
       KUBECONFIG: /etc/rancher/k3s/k3s.yaml
+      SOCKET_FILE: /etc/vault-kms-provider.sock
       ENCRYPTION_CONFIG: /tmp/encryption/configuration.yaml
       K3S_DATASTORE_ENDPOINT: https://127.0.0.1:2379
       K3S_DATASTORE_CAFILE: /tmp/certs/server.crt
@@ -320,7 +321,13 @@ jobs:
       - run:
           name: Check for socket file
           command: |
-            [[ -f /etc/vault-kms-provider.sock ]] && exit 0 || exit 1
+            if [ -f  "$SOCKET_FILE" ]; then
+              echo "found socket file"
+              exit 0
+            else
+              echo "file not found"
+              exit 1
+            fi
       - run:
           name: Create encryption configuration
           command: |
